import { useEffect, useRef, useState } from 'react'
import './App.css'
import './theme.css'

const tags = ['Python', 'Machine Learning', 'Generative AI', 'RAG', 'Agentic AI', 'Databricks', 'Analytics']
const projects = [
  { number: '01', eyebrow: 'Agentic AI · Customer support', title: 'From customer email to autonomous resolution.', problem: 'Large volumes of support emails required manual reading, classification, Salesforce updates and responses.', solution: 'Designed Agentic AI workflows that understand requests, apply business logic, update Salesforce, select relevant responses and resolve eligible cases automatically.', impact: '~75% of daily support tickets automated / auto-closed.', tech: ['Python', 'NLP', 'Agentic AI', 'REST APIs', 'Salesforce Integration', 'Automation'], flow: ['Customer Email', 'Intent Understanding', 'Business Logic', 'Salesforce Action', 'Response Generation', 'Auto Resolution'] },
  { number: '02', eyebrow: 'RAG · Data platform', title: 'Ask your data in natural language.', problem: 'Non-technical users depended on engineering teams to understand database structures and locate the right data.', solution: 'Built a RAG-powered AI data dictionary so teams can query enterprise data knowledge using natural-language questions.', impact: '100+ users · 40% faster onboarding · 300+ engineering hours saved quarterly.', tech: ['RAG', 'Generative AI', 'Python', 'SQL', 'Databricks', 'NLP'], flow: ['User Question', 'Retrieval', 'Context Selection', 'LLM', 'Answer'] },
  { number: '03', eyebrow: 'Machine learning · Decision support', title: 'Turning partner selection into a data-driven decision.', problem: 'Manual partner selection made it difficult to compare signals consistently and move quickly.', solution: 'Built a 50-feature machine-learning model and a lightweight serving layer that translates partner data into an actionable score.', impact: '25% improvement in sales win rate · 35+ daily users.', tech: ['Python', 'Scikit-learn', 'Feature Engineering', 'FastAPI', 'Power BI'], flow: ['Raw Partner Data', 'Feature Engineering', 'ML Model', 'Partner Score', 'Business Decision'] },
]
const secondaryProjects = [['04', 'Self-service analytics platform', 'Analytics tooling for funnel, cohort, retention and conversion analysis across 6 business units.', '6 business units'], ['05', 'Catalogue intelligence', 'Automated monitoring across 10K+ catalogue listings using Python and SQL pipelines.', '18% increase in lab bookings'], ['06', 'Checkout funnel optimization', 'Analyzed customer checkout behavior, found drop-off points and contributed to product improvements.', '25% completion lift · 18% cashless growth']]
const explorationProjects = [['AudiEyes: See the Unseen', 'https://sites.google.com/view/vaibhav-chopra-portfolio/projects/audi-eyes'], ['AI Bot Agent', 'https://sites.google.com/view/vaibhav-chopra-portfolio/projects/bot-agent'], ['BasketBlend: Smart Shopping Synergy', 'https://sites.google.com/view/vaibhav-chopra-portfolio/projects/basket-blend'], ['NewsNest: Sorting Stories with NLP', 'https://sites.google.com/view/vaibhav-chopra-portfolio/projects/news-nest']]
const metrics = [['75', '%', 'Support tickets automated'], ['95', '%', 'Lab report matching accuracy'], ['300', '+', 'Engineering hours saved quarterly'], ['100', '+', 'Users on AI data solution'], ['25', '%', 'Sales win-rate improvement'], ['24', '%', 'Organic discovery improvement'], ['6', '', 'Business units using self-service analytics']]
const stack = { 'AI & ML': ['Python', 'Scikit-learn', 'TensorFlow', 'PyTorch', 'NLP', 'Deep Learning', 'Time Series', 'RAG', 'Agentic AI', 'Generative AI'], Data: ['SQL', 'Databricks', 'Pandas', 'NumPy', 'Airflow', 'Elasticsearch'], Deployment: ['FastAPI', 'REST APIs', 'Docker', 'Git', 'Linux'], Analytics: ['A/B Testing', 'Funnel Analysis', 'Cohort Analysis', 'Retention Analysis', 'Conversion Analysis'], Visualization: ['Power BI', 'Looker Studio', 'Google Analytics'] }

function App() {
  const [dark, setDark] = useState(true); const [menuOpen, setMenuOpen] = useState(false); const [selectedProject, setSelectedProject] = useState(null); const [activeSection, setActiveSection] = useState('work')
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; document.title = 'Vaibhav Chopra | Senior Data Scientist & AI Engineer' }, [dark])
  useEffect(() => { const revealObserver = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: 0.12 }); const sectionObserver = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: '-35% 0px -55%' }); document.querySelectorAll('.reveal').forEach((element) => revealObserver.observe(element)); document.querySelectorAll('main section[id]').forEach((element) => sectionObserver.observe(element)); return () => { revealObserver.disconnect(); sectionObserver.disconnect() } }, [])
  const closeMenu = () => setMenuOpen(false)

  return (
    <div className="site-shell"><header className="navbar"><a className="brand" href="#top" onClick={closeMenu}><span>VC</span><strong>Vaibhav Chopra</strong></a><button className="menu-toggle" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? '×' : '☰'}</button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><a className={activeSection === 'work' ? 'active' : ''} href="#work" onClick={closeMenu}>Work</a><a className={activeSection === 'lab' ? 'active' : ''} href="#lab" onClick={closeMenu}>Lab</a><a className={activeSection === 'thinking' ? 'active' : ''} href="#thinking" onClick={closeMenu}>Approach</a><a className={activeSection === 'about' ? 'active' : ''} href="#about" onClick={closeMenu}>About</a><a className="nav-contact" href="#contact" onClick={closeMenu}>Let's talk <span>↗</span></a></nav><button className="theme-toggle" aria-label="Toggle color theme" onClick={() => setDark(!dark)}>{dark ? '☼' : '◐'}</button></header>
      <main id="top"><section className="hero section-pad" id="hero"><div className="hero-copy reveal"><p className="eyebrow"><span className="live-dot" /> Senior Data Scientist @ Bajaj Finserv Health · Pune, India</p><h1>Building AI systems that <em>actually work</em> in production.</h1><p className="hero-intro">I design intelligent products for the messy middle between a business problem and a measurable outcome. Over 4.2 years, I have grown from intern to Senior Data Scientist across analytics, machine learning and Generative AI.</p><div className="hero-actions"><a className="button button-dark" href="#work">Explore my work <span>↘</span></a><a className="text-link" href="#contact">Get in touch <span>↗</span></a></div><div className="tag-list">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><div className="hero-visual reveal reveal-delay"><div className="orbital orbital-one" /><div className="orbital orbital-two" /><div className="core"><span>AI</span><small>systems<br />in motion</small></div><div className="node node-a">RAG</div><div className="node node-b">ML</div><div className="node node-c">API</div><div className="node node-d">∞</div><svg className="connections" viewBox="0 0 500 500" aria-hidden="true"><path d="M250 250 L100 112 M250 250 L402 135 M250 250 L414 365 M250 250 L85 382" /><path d="M100 112 L402 135 M402 135 L414 365 M414 365 L85 382" /></svg><div className="visual-label">01 <span>/</span> BUILDING THE FUTURE</div></div><div className="hero-metrics reveal"><div><strong>4.2<span>+</span></strong><small>years experience</small></div><div><strong>75<span>%</span></strong><small>support automated</small></div><div><strong>300<span>+</span></strong><small>hours saved / qtr</small></div><div><strong>25<span>%</span></strong><small>sales-win uplift</small></div></div></section>
      <section className="build-section section-pad" id="build"><div className="section-intro reveal"><p className="section-kicker">/ 01 — WHAT I BUILD</p><h2>Useful intelligence,<br /><em>beautifully shipped.</em></h2><p>Not models in notebooks. Systems with users, edge cases, business logic and an opinion about what happens next.</p></div><div className="build-grid reveal reveal-delay">{[['01', 'Production AI Systems', 'Automation that understands requests, applies business logic, interacts with enterprise tools and takes action.'], ['02', 'LLM & RAG Applications', 'Grounded interfaces that turn scattered enterprise knowledge into confident, useful answers.'], ['03', 'Machine Learning Products', 'Models translated into decisions, scores and workflows people can use every day.'], ['04', 'Analytics & Experimentation', 'Clear answers to complex product questions, from funnel friction to retention signals.']].map(([num, title, copy]) => <article className="build-card" key={title}><span className="card-number">{num}</span><div><h3>{title}</h3><p>{copy}</p></div><span className="card-arrow">↗</span></article>)}</div></section>
      <section className="work-section section-pad" id="work"><div className="section-header reveal"><div><p className="section-kicker">/ 02 — SELECTED WORK</p><h2>Case studies from<br /><em>the real world.</em></h2></div><p className="section-note">A few systems, experiments and decisions I’ve helped move from idea to impact.</p></div><div className="project-list">{projects.map((project) => <ProjectCard key={project.number} project={project} onOpen={() => setSelectedProject(project)} />)}</div><div className="secondary-projects reveal">{secondaryProjects.map(([number, title, copy, impact]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p><strong>{impact}</strong></div><span className="card-arrow">↗</span></article>)}</div></section>
      <section className="impact-section section-pad" id="impact"><div className="section-intro reveal"><p className="section-kicker">/ 03 — IMPACT BY NUMBERS</p><h2>Outcomes over<br /><em>output.</em></h2></div><div className="metrics-grid reveal reveal-delay">{metrics.map(([number, suffix, label]) => <Metric key={label} number={number} suffix={suffix} label={label} />)}</div></section>
      <section className="lab-section section-pad" id="lab"><div className="section-header reveal"><div><p className="section-kicker">/ 04 — THE AI / ML LAB</p><h2>Things I like<br /><em>building.</em></h2></div><p className="section-note">Curiosity is a practical tool. I keep a small lab for ideas that might become useful systems.</p></div><div className="lab-grid reveal reveal-delay">{['RAG Systems', 'AI Agents', 'Intelligent Automation', 'Recommendation Systems', 'NLP Systems', 'ML APIs', 'Analytics Platforms', 'Experimentation Systems'].map((item, index) => <div className="lab-card" key={item}><span>0{index + 1}</span><h3>{item}</h3><i>↗</i></div>)}</div></section>
      <section className="thinking-section section-pad" id="thinking"><div className="thinking-copy reveal"><p className="section-kicker">/ 05 — HOW I THINK</p><h2>Start with the problem.<br /><em>Stay for the impact.</em></h2><p>“I focus less on building models for the sake of models and more on solving measurable business problems.”</p></div><div className="thinking-flow reveal reveal-delay">{['Business Problem', 'Data Understanding', 'Hypothesis', 'Prototype', 'Validate', 'Productionize', 'Measure Impact'].map((step, index) => <div key={step}><span>0{index + 1}</span><strong>{step}</strong>{index < 6 && <i>→</i>}</div>)}</div></section>
      <section className="stack-section section-pad" id="stack"><div className="section-intro reveal"><p className="section-kicker">/ 06 — TOOLKIT</p><h2>A stack for<br /><em>shipping.</em></h2></div><div className="stack-grid reveal reveal-delay">{Object.entries(stack).map(([category, tools]) => <div className="stack-group" key={category}><h3>{category}</h3><div>{tools.map((tool) => <span key={tool}>{tool}</span>)}</div></div>)}</div></section>
      <section className="about-section section-pad" id="about"><div className="achievements reveal"><p className="section-kicker">/ 07 — PROOF OF WORK</p><h2>Small signals,<br /><em>over time.</em></h2><div className="achievement-list">{['Google TensorFlow Developer Certification — Top 5% worldwide', 'Kaggle Expert — Dataset Expert, highest rank 500', '9.97 / 10 CGPA — Chitkara University', 'JP Morgan Code for Good 2022 Runner-up', 'Open-source Python package — 500+ installs', '6-star Gold HackerRank badge — 2,000+ problems solved', '1 Sharp Shark, 3 Limelight and 1 Stellar Squad awards at Bajaj Finserv Health'].map((item, index) => <div key={item}><span>0{index + 1}</span><p>{item}</p></div>)}</div></div><div className="journey reveal reveal-delay"><p className="section-kicker">/ CAREER JOURNEY</p><div className="journey-line">{['Intern · Jun 2022 – Jul 2023', 'Product Analyst · Jul 2023 – Jan 2024', 'Associate Data Scientist · Jan 2024 – Oct 2024', 'Data Scientist · Nov 2024 – Apr 2026', 'Senior Data Scientist · May 2026 – Present'].map((item, index) => <div className={index === 4 ? 'current' : ''} key={item}><span>{index + 1}</span><strong>{item}</strong></div>)}</div><div className="education"><p className="section-kicker">/ EDUCATION</p><strong>B.E. Computer Science · Data Science specialization</strong><span>Chitkara University · Rajpura, Punjab · 2019 – 2023</span></div><div className="beyond"><p className="section-kicker">/ BEYOND MODELS</p><p>I enjoy turning ambiguous business problems into simple, measurable technical solutions. I’m particularly interested in AI systems that interact with real users and real workflows.</p></div></div></section>
      <section className="explore-section section-pad" id="explore"><div className="section-header reveal"><div><p className="section-kicker">/ 08 — KEEP EXPLORING</p><h2>Things I think<br /><em>about.</em></h2></div></div><div className="explore-grid reveal reveal-delay">{['Why AI automation fails in production', 'RAG vs traditional search', 'What makes a useful ML model', 'From prototype to production AI', 'Measuring business impact in Data Science'].map((item, index) => <a href="#contact" key={item}><span>0{index + 1}</span><h3>{item}</h3><i>↗</i></a>)}</div><div className="open-source"><span className="section-kicker">/ SELF-PROJECTS</span>{explorationProjects.map(([title, url]) => <a href={url} target="_blank" rel="noreferrer" key={title}>{title} <span>↗</span></a>)}<a href="https://www.kaggle.com/vaibhavchopra2" target="_blank" rel="noreferrer">Kaggle <span>↗</span></a><a href="https://www.hackerrank.com/Brainy_Eagle22?hr_r=1" target="_blank" rel="noreferrer">HackerRank <span>↗</span></a></div></section>
      <section className="contact-section section-pad" id="contact"><div className="contact-inner reveal"><p className="section-kicker">/ 09 — CONTACT</p><h2>Let’s build<br /><em>something useful.</em></h2><p>Have a difficult problem, an early idea, or a team building at the edge of what’s possible?<br /><a href="mailto:vaibhavchopra039@gmail.com">vaibhavchopra039@gmail.com</a> · <a href="tel:+917015867715">+91 70158 67715</a></p><a className="button button-light" href="mailto:vaibhavchopra039@gmail.com">Say hello <span>↗</span></a></div></section></main><footer><span>© 2026 Vaibhav Chopra</span><span>Senior Data Scientist / AI Engineer · Pune, India</span><div><a href="https://www.linkedin.com/in/vaibhav-chopra-4a226a21b/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://www.kaggle.com/vaibhavchopra2" target="_blank" rel="noreferrer">Kaggle</a><a href="mailto:vaibhavchopra039@gmail.com">Email</a></div></footer>{selectedProject && <CaseStudyModal project={selectedProject} onClose={() => setSelectedProject(null)} />}</div>
  )
}

function ProjectCard({ project, onOpen }) { return <article className="project-card reveal"><div className="project-top"><span className="project-number">{project.number}</span><span className="project-eyebrow">{project.eyebrow}</span><button className="case-study-button" onClick={onOpen}>View case study <span>↗</span></button></div><div className="project-body"><div className="project-copy"><h3>{project.title}</h3><p>{project.solution}</p><strong>{project.impact}</strong><div className="tech-pills">{project.tech.map((tech) => <span key={tech}>{tech}</span>)}</div></div><div className="flow"><span className="flow-label">SYSTEM FLOW</span>{project.flow.map((step, index) => <div className="flow-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < project.flow.length - 1 && <i>↓</i>}</div>)}</div></div></article> }
function Metric({ number, suffix, label }) { const ref = useRef(null); const [count, setCount] = useState(0); useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { let start = 0; const end = Number(number); const timer = setInterval(() => { start += Math.max(1, Math.ceil(end / 28)); if (start >= end) { start = end; clearInterval(timer) } setCount(start) }, 35); observer.disconnect() } }, { threshold: 0.7 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect() }, [number]); return <div className="metric" ref={ref}><strong>{count}<span>{suffix}</span></strong><p>{label}</p></div> }
function CaseStudyModal({ project, onClose }) { useEffect(() => { document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = '' } }, []); return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><span className="section-kicker">/ CASE STUDY {project.number}</span><h2>{project.title}</h2><div className="modal-columns"><div><h3>The problem</h3><p>{project.problem}</p></div><div><h3>The approach</h3><p>{project.solution}</p></div></div><div className="modal-impact"><span>Outcome</span><strong>{project.impact}</strong></div><div className="tech-pills">{project.tech.map((tech) => <span key={tech}>{tech}</span>)}</div></div></div> }

export default App
