import { useEffect, useRef, useState } from 'react'
import './App.css'
import './theme.css'
import profileImage from './assets/profile.jpg'
import officeImage from './assets/bfhl-office.jpg'

const tags = ['Python', 'Machine Learning', 'Generative AI', 'RAG', 'Agentic AI', 'Databricks', 'Analytics']
const projects = [
  { number: '01', eyebrow: 'Agentic AI · Customer support', title: 'From customer email to autonomous resolution.', problem: 'Large volumes of support emails required manual reading, classification, Salesforce updates and responses.', solution: 'Designed Agentic AI workflows that understand requests, apply business logic, update Salesforce, select relevant responses and resolve eligible cases automatically.', impact: '~75% of daily support tickets automated / auto-closed.', detail: 'A production workflow that moves from unstructured customer intent to a governed business action without exposing confidential customer or internal system details.', architecture: 'Intent understanding → business rules → enterprise action → grounded response → resolution', tech: ['Python', 'NLP', 'Agentic AI', 'REST APIs', 'Salesforce Integration', 'Automation'], flow: ['Customer Email', 'Intent Understanding', 'Business Logic', 'Salesforce Action', 'Response Generation', 'Auto Resolution'] },
  { number: '02', eyebrow: 'RAG · Data platform', title: 'Ask your data in natural language.', problem: 'Non-technical users depended on engineering teams to understand database structures and locate the right data.', solution: 'Built a RAG-powered AI data dictionary so teams can query enterprise data knowledge using natural-language questions.', impact: '100+ users · 40% faster onboarding · 300+ engineering hours saved quarterly.', detail: 'The system turns fragmented data knowledge into a searchable, explainable interface, helping users find the right context before asking engineering for help.', architecture: 'Question → retrieval → context selection → LLM answer with grounded context', tech: ['RAG', 'Generative AI', 'Python', 'SQL', 'Databricks', 'NLP'], flow: ['User Question', 'Retrieval', 'Context Selection', 'LLM', 'Answer'] },
  { number: '03', eyebrow: 'Machine learning · Decision support', title: 'Turning partner selection into a data-driven decision.', problem: 'Manual partner selection made it difficult to compare signals consistently and move quickly.', solution: 'Built a 50-feature machine-learning model and a lightweight serving layer that translates partner data into an actionable score.', impact: '25% improvement in sales win rate · 35+ daily users.', detail: 'A model-led decision product that combines feature engineering, an API layer and a Power BI surface so the score becomes part of the daily operating rhythm.', architecture: 'Raw partner data → engineered features → model score → business decision', tech: ['Python', 'Scikit-learn', 'Feature Engineering', 'FastAPI', 'Power BI'], flow: ['Raw Partner Data', 'Feature Engineering', 'ML Model', 'Partner Score', 'Business Decision'] },
]
const secondaryProjects = [
  { number: '04', eyebrow: 'Analytics · Self-service', title: 'Analytics without writing SQL.', problem: 'Business teams needed engineering support for recurring funnel, cohort, retention and conversion questions.', solution: 'Built self-serve analytics tooling that makes repeatable product analysis accessible to non-technical teams.', impact: 'Used across 6 business units.', detail: 'The focus was not another dashboard. It was a reusable analysis workflow that shortened the distance between a question and a decision.', architecture: 'Business question → reusable analysis → visual insight → action', tech: ['Python', 'SQL', 'Analytics', 'Visualization'], flow: ['Business Question', 'Select Analysis', 'Explore Data', 'Read Insight', 'Take Action'] },
  { number: '05', eyebrow: 'Data automation · Operations', title: 'Making catalogue health observable.', problem: 'Gaps across 10K+ catalogue listings were difficult to identify and act on manually.', solution: 'Automated catalogue health monitoring with Python and SQL pipelines that flag issues early.', impact: '18% increase in lab bookings.', detail: 'A practical data quality system that connected monitoring signals to an outcome the business could measure.', architecture: 'Catalogue data → quality checks → issue flags → operational correction', tech: ['Python', 'SQL', 'Pipelines', 'Monitoring'], flow: ['Catalogue Data', 'Health Checks', 'Issue Detection', 'Team Action', 'Booking Lift'] },
  { number: '06', eyebrow: 'Product analytics · Growth', title: 'Finding the friction in checkout.', problem: 'Customer checkout behaviour contained several hidden drop-off points and payment adoption barriers.', solution: 'Used funnel deep-dives and product experiments to isolate friction and guide checkout improvements.', impact: '25% completion lift · 18% cashless payment growth.', detail: 'The work connected behavioural evidence to shipped product changes rather than stopping at a report.', architecture: 'Customer behaviour → funnel diagnosis → experiment → product improvement', tech: ['Funnel Analysis', 'A/B Testing', 'SQL', 'Google Analytics'], flow: ['User Journey', 'Drop-off Analysis', 'Hypothesis', 'Experiment', 'Conversion Lift'] },
]
const explorationProjects = [
  { number: 'A1', eyebrow: 'Deep learning · Accessibility', title: 'AudiEyes: See the Unseen.', problem: 'Visual scenes are difficult to access for people who cannot rely on sight.', solution: 'Built a TensorFlow Hub and COCO model-powered scene analysis concept that processes video or camera frames and turns detected visual context into meaningful audio experiences.', detail: 'An accessibility-led exploration of how computer vision can translate the world around a person into useful, timely feedback.', architecture: 'Video or camera frames → COCO scene analysis → classified context → auditory experience', impact: 'Accessibility-focused computer vision prototype.', tech: ['Python', 'TensorFlow Hub', 'Computer Vision', 'Deep Learning'], flow: ['Camera / Video', 'Frame Extraction', 'Scene Analysis', 'Classify Context', 'Audio Output'], url: 'https://sites.google.com/view/vaibhav-chopra-portfolio/projects/audi-eyes' },
  { number: 'A2', eyebrow: 'Reinforcement learning · Simulation', title: 'AI Bot Agent.', problem: 'An agent needs to learn useful actions in an environment where the best path is not given upfront.', solution: 'Implemented a Q-learning agent for the FrozenLake environment using Gym, balancing exploration with actions learned through repeated trials.', detail: 'A compact reinforcement-learning experiment that makes the learning loop visible: try, observe, update the value function, and improve the next decision.', architecture: 'Environment state → action selection → reward → Q-table update → learned policy', impact: 'Q-learning agent trained in a changing environment.', tech: ['Python', 'Q-learning', 'Gym', 'Reinforcement Learning'], flow: ['FrozenLake State', 'Choose Action', 'Receive Reward', 'Update Q-table', 'Improve Policy'], url: 'https://sites.google.com/view/vaibhav-chopra-portfolio/projects/bot-agent' },
  { number: 'A3', eyebrow: 'Recommendation systems · Retail', title: 'BasketBlend: Smart Shopping Synergy.', problem: 'Purchase history contains item relationships that are easy to miss when shopping one product at a time.', solution: 'Used the Apriori algorithm to discover item associations in purchase history and surface complementary recommendations.', detail: 'A practical association-rule mining project that turns transactions into shopping suggestions and shows how pattern discovery can improve product discovery.', architecture: 'Purchase history → frequent item sets → association rules → complementary suggestions', impact: 'Recommendation prototype based on purchase associations.', tech: ['Python', 'Apriori', 'Association Rules', 'Recommendation Systems'], flow: ['Purchase History', 'Find Item Sets', 'Learn Associations', 'Rank Rules', 'Suggest Items'], url: 'https://sites.google.com/view/vaibhav-chopra-portfolio/projects/basket-blend' },
  { number: 'A4', eyebrow: 'NLP · Text classification', title: 'NewsNest: Sorting Stories with NLP.', problem: 'Large collections of news articles are difficult to organize and search without meaningful categories.', solution: 'Built an NLP classification pipeline using logistic regression to categorize BBC News articles into useful story groups.', detail: 'The project demonstrates a complete classical NLP loop from raw text to a measurable classifier, with a reported 97% accuracy on the source dataset.', architecture: 'Raw article text → text features → logistic regression → story category', impact: '97% reported classification accuracy on BBC News data.', tech: ['Python', 'NLP', 'Logistic Regression', 'Text Classification'], flow: ['BBC Article', 'Text Features', 'Train Classifier', 'Predict Category', 'Organize Stories'], url: 'https://sites.google.com/view/vaibhav-chopra-portfolio/projects/news-nest' },
]
const metrics = [['75', '%', 'Support tickets automated'], ['95', '%', 'Lab report matching accuracy'], ['300', '+', 'Engineering hours saved quarterly'], ['100', '+', 'Users on AI data solution'], ['25', '%', 'Sales win-rate improvement'], ['24', '%', 'Organic discovery improvement'], ['6', '', 'Business units using self-service analytics']]
const stack = { 'AI & ML': ['Python', 'Scikit-learn', 'TensorFlow', 'PyTorch', 'NLP', 'Deep Learning', 'Time Series', 'RAG', 'Agentic AI', 'Generative AI'], Data: ['SQL', 'Databricks', 'Pandas', 'NumPy', 'Airflow', 'Elasticsearch'], Deployment: ['FastAPI', 'REST APIs', 'Docker', 'Git', 'Linux'], Analytics: ['A/B Testing', 'Funnel Analysis', 'Cohort Analysis', 'Retention Analysis', 'Conversion Analysis'], Visualization: ['Power BI', 'Looker Studio', 'Google Analytics'] }
const searchItems = [
  { type: 'Experience', title: 'Senior Data Scientist at Bajaj Finserv Health', text: 'Vaibhav has 4.2+ years of experience, progressing from intern to Senior Data Scientist in Pune, India.', href: '#about' },
  { type: 'Project', title: 'Agentic AI customer support', text: 'Built workflows that understand customer intent, apply business logic, update enterprise tools and auto-close nearly 75% of daily support tickets.', href: '#work' },
  { type: 'Project', title: 'RAG-powered AI data dictionary', text: 'Built a natural-language data discovery solution used by 100+ users, reducing onboarding time by 40% and saving 300+ engineering hours quarterly.', href: '#work' },
  { type: 'Project', title: 'Partner scoring engine', text: 'Built a 50-feature machine-learning model and API that improved sales win rate by 25% and supports 35+ daily users.', href: '#work' },
  { type: 'Award', title: 'TensorFlow Developer Certification', text: 'Google TensorFlow Developer certified, with a reported top 5% worldwide result.', href: '#about' },
  { type: 'Award', title: 'Kaggle Expert and HackerRank Gold', text: 'Kaggle Expert with a highest rank of 500, plus a 6-star Gold HackerRank badge and 2,000+ problems solved.', href: '#about' },
  { type: 'Skill', title: 'AI and engineering toolkit', text: 'Python, RAG, Agentic AI, Generative AI, NLP, SQL, Databricks, FastAPI, Docker, Power BI and experimentation.', href: '#stack' },
  { type: 'Independent Build', title: 'AudiEyes, NewsNest and more', text: 'Independent projects span accessibility-focused computer vision, reinforcement learning, recommendation systems and NLP.', href: '#explore' },
]

function App() {
  const [dark, setDark] = useState(true); const [menuOpen, setMenuOpen] = useState(false); const [selectedProject, setSelectedProject] = useState(null); const [activeSection, setActiveSection] = useState('work')
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; document.title = 'Vaibhav Chopra | Senior Data Scientist & AI Engineer' }, [dark])
  useEffect(() => { const revealObserver = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: 0.12 }); const sectionObserver = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: '-35% 0px -55%' }); document.querySelectorAll('.reveal').forEach((element) => revealObserver.observe(element)); document.querySelectorAll('main section[id]').forEach((element) => sectionObserver.observe(element)); return () => { revealObserver.disconnect(); sectionObserver.disconnect() } }, [])
  const closeMenu = () => setMenuOpen(false)

  return (
    <div className="site-shell"><header className="navbar"><a className="brand" href="#top" onClick={closeMenu}><span>VC</span><strong>Vaibhav Chopra</strong></a><button className="menu-toggle" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? '×' : '☰'}</button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><a className={activeSection === 'work' ? 'active' : ''} href="#work" onClick={closeMenu}>Work</a><a href="#explore" onClick={closeMenu}>Projects</a><a className={activeSection === 'lab' ? 'active' : ''} href="#lab" onClick={closeMenu}>Lab</a><a className={activeSection === 'thinking' ? 'active' : ''} href="#thinking" onClick={closeMenu}>Approach</a><a className={activeSection === 'about' ? 'active' : ''} href="#about" onClick={closeMenu}>About</a><a className="nav-contact" href="#contact" onClick={closeMenu}>Let's talk <span>↗</span></a></nav><button className="theme-toggle" aria-label="Toggle color theme" onClick={() => setDark(!dark)}>{dark ? '☼' : '◐'}</button></header>
        <main id="top"><section className="hero section-pad" id="hero"><div className="hero-copy reveal"><p className="eyebrow"><span className="live-dot" /> Senior Data Scientist @ Bajaj Finserv Health · Pune, India</p><h1>Building AI systems that <em>actually work</em> in production.</h1><p className="hero-intro">I design intelligent products for the messy middle between a business problem and a measurable outcome. Over 4.2 years, I have grown from intern to Senior Data Scientist across analytics, machine learning and Generative AI.</p><div className="hero-actions"><a className="button button-dark" href="#work">Explore my work <span>↘</span></a><a className="text-link" href="#contact">Get in touch <span>↗</span></a></div><div className="tag-list">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><div className="hero-visual reveal reveal-delay"><div className="orbital orbital-one" /><div className="orbital orbital-two" /><div className="core"><img src={profileImage} alt="Vaibhav Chopra" /><small>systems<br />in motion</small></div><div className="node node-a">RAG</div><div className="node node-b">ML</div><div className="node node-c">API</div><div className="node node-d">∞</div><svg className="connections" viewBox="0 0 500 500" aria-hidden="true"><path d="M250 250 L100 112 M250 250 L402 135 M250 250 L414 365 M250 250 L85 382" /><path d="M100 112 L402 135 M402 135 L414 365 M414 365 L85 382" /></svg><div className="visual-label">01 <span>/</span> BUILDING AI SYSTEMS</div></div><div className="hero-metrics reveal"><div><strong>4.2<span>+</span></strong><small>years experience</small></div><div><strong>75<span>%</span></strong><small>support automated</small></div><div><strong>300<span>+</span></strong><small>hours saved / qtr</small></div><div><strong>25<span>%</span></strong><small>sales-win uplift</small></div></div></section><AskVaibhav />
      <section className="build-section section-pad" id="build"><div className="section-intro reveal"><p className="section-kicker">/ 01 — WHAT I BUILD</p><h2>Useful intelligence,<br /><em>beautifully shipped.</em></h2><p>Not models in notebooks. Systems with users, edge cases, business logic and an opinion about what happens next.</p></div><div className="build-grid reveal reveal-delay">{[['01', 'Production AI Systems', 'Automation that understands requests, applies business logic, interacts with enterprise tools and takes action.'], ['02', 'LLM & RAG Applications', 'Grounded interfaces that turn scattered enterprise knowledge into confident, useful answers.'], ['03', 'Machine Learning Products', 'Models translated into decisions, scores and workflows people can use every day.'], ['04', 'Analytics & Experimentation', 'Clear answers to complex product questions, from funnel friction to retention signals.']].map(([num, title, copy]) => <article className="build-card" key={title}><span className="card-number">{num}</span><div><h3>{title}</h3><p>{copy}</p></div><span className="card-arrow">↗</span></article>)}</div></section>
      <section className="work-section section-pad" id="work"><div className="section-header reveal"><div><p className="section-kicker">/ 02 — SELECTED WORK</p><h2>Case studies from<br /><em>the real world.</em></h2></div><p className="section-note">A few systems, experiments and decisions I’ve helped move from idea to impact.</p></div><div className="project-list">{projects.map((project) => <ProjectCard key={project.number} project={project} onOpen={() => setSelectedProject(project)} />)}</div><div className="secondary-projects reveal">{secondaryProjects.map((project) => <SecondaryProjectCard key={project.number} project={project} onOpen={() => setSelectedProject(project)} />)}</div></section>
      <section className="impact-section section-pad" id="impact"><div className="section-intro reveal"><p className="section-kicker">/ 03 — IMPACT BY NUMBERS</p><h2>Outcomes over<br /><em>output.</em></h2></div><div className="metrics-grid reveal reveal-delay">{metrics.map(([number, suffix, label]) => <Metric key={label} number={number} suffix={suffix} label={label} />)}</div></section><section className="bfhl-section" id="bfhl"><div className="bfhl-image-wrap reveal"><img src={officeImage} alt="Vaibhav Chopra at Bajaj Finserv Health" /><div className="bfhl-overlay"><span className="section-kicker">/ PRODUCTION CONTEXT</span><h2>Built close to<br /><em>real healthcare workflows.</em></h2><p>Bajaj Finserv Health · Pune, India</p></div><span className="bfhl-index">03 <i>/</i> 09</span></div></section>
      <section className="lab-section section-pad" id="lab"><div className="section-header reveal"><div><p className="section-kicker">/ 04 — THE AI / ML LAB</p><h2>Things I like<br /><em>building.</em></h2></div><p className="section-note">Curiosity is a practical tool. I keep a small lab for ideas that might become useful systems.</p></div><div className="lab-grid reveal reveal-delay">{['RAG Systems', 'AI Agents', 'Intelligent Automation', 'Recommendation Systems', 'NLP Systems', 'ML APIs', 'Analytics Platforms', 'Experimentation Systems'].map((item, index) => <div className="lab-card" key={item}><span>0{index + 1}</span><h3>{item}</h3><i>↗</i></div>)}</div></section>
      <section className="thinking-section section-pad" id="thinking"><div className="thinking-copy reveal"><p className="section-kicker">/ 05 — HOW I THINK</p><h2>Start with the problem.<br /><em>Stay for the impact.</em></h2><p>“I focus less on building models for the sake of models and more on solving measurable business problems.”</p></div><div className="thinking-flow reveal reveal-delay">{['Business Problem', 'Data Understanding', 'Hypothesis', 'Prototype', 'Validate', 'Productionize', 'Measure Impact'].map((step, index) => <div key={step}><span>0{index + 1}</span><strong>{step}</strong>{index < 6 && <i>→</i>}</div>)}</div></section>
      <section className="stack-section section-pad" id="stack"><div className="section-intro reveal"><p className="section-kicker">/ 06 — TOOLKIT</p><h2>A stack for<br /><em>shipping.</em></h2></div><div className="stack-grid reveal reveal-delay">{Object.entries(stack).map(([category, tools]) => <div className="stack-group" key={category}><h3>{category}</h3><div>{tools.map((tool) => <span key={tool}>{tool}</span>)}</div></div>)}</div></section>
      <section className="about-section section-pad" id="about"><div className="achievements reveal"><p className="section-kicker">/ 07 — PROOF OF WORK</p><h2>Small signals,<br /><em>over time.</em></h2><div className="achievement-list">{['Google TensorFlow Developer Certification — Top 5% worldwide', 'Kaggle Expert — Dataset Expert, highest rank 500', '9.97 / 10 CGPA — Chitkara University', 'JP Morgan Code for Good 2022 Runner-up', 'Open-source Python package — 500+ installs', '6-star Gold HackerRank badge — 2,000+ problems solved', '1 Sharp Shark, 3 Limelight and 1 Stellar Squad awards at Bajaj Finserv Health'].map((item, index) => <div key={item}><span>0{index + 1}</span><p>{item}</p></div>)}</div></div><div className="journey reveal reveal-delay"><p className="section-kicker">/ CAREER JOURNEY</p><div className="journey-line">{['Intern · Jun 2022 – Jul 2023', 'Product Analyst · Jul 2023 – Jan 2024', 'Associate Data Scientist · Jan 2024 – Oct 2024', 'Data Scientist · Nov 2024 – Apr 2026', 'Senior Data Scientist · May 2026 – Present'].map((item, index) => <div className={index === 4 ? 'current' : ''} key={item}><span>{index + 1}</span><strong>{item}</strong></div>)}</div><div className="education"><p className="section-kicker">/ EDUCATION</p><strong>B.E. Computer Science · Data Science specialization</strong><span>Chitkara University · Rajpura, Punjab · 2019 – 2023</span></div><div className="beyond"><p className="section-kicker">/ BEYOND MODELS</p><p>I enjoy turning ambiguous business problems into simple, measurable technical solutions. I’m particularly interested in AI systems that interact with real users and real workflows.</p></div></div></section>
      <section className="explore-section section-pad" id="explore"><div className="section-header reveal"><div><p className="section-kicker">/ 08 — KEEP EXPLORING</p><h2>Things I think<br /><em>about.</em></h2></div></div><div className="explore-grid reveal reveal-delay">{['Why AI automation fails in production', 'RAG vs traditional search', 'What makes a useful ML model', 'From prototype to production AI', 'Measuring business impact in Data Science'].map((item, index) => <a href="#contact" key={item}><span>0{index + 1}</span><h3>{item}</h3><i>↗</i></a>)}</div><div className="independent-builds"><div className="independent-heading"><p className="section-kicker">/ INDEPENDENT BUILDS</p><p>Earlier experiments that show the range behind the production work: vision, reinforcement learning, recommendations and NLP.</p></div><div className="independent-grid">{explorationProjects.map((project) => <article className="independent-card" key={project.number} onClick={() => setSelectedProject(project)} onKeyDown={(event) => event.key === 'Enter' && setSelectedProject(project)} role="button" tabIndex="0"><div><span>{project.number}</span><small>{project.eyebrow}</small></div><h3>{project.title}</h3><p>{project.solution}</p><strong>{project.impact}</strong><i>↗</i></article>)}</div></div><div className="open-source"><span className="section-kicker">/ REFERENCES</span><a href="https://www.kaggle.com/vaibhavchopra2" target="_blank" rel="noreferrer">Kaggle <span>↗</span></a><a href="https://www.hackerrank.com/Brainy_Eagle22?hr_r=1" target="_blank" rel="noreferrer">HackerRank <span>↗</span></a></div></section>
      <section className="contact-section section-pad" id="contact"><div className="contact-inner reveal"><p className="section-kicker">/ 09 — CONTACT</p><h2>Let’s build<br /><em>something useful.</em></h2><p>Have a difficult problem, an early idea, or a team building at the edge of what’s possible?<br /><a href="mailto:vaibhavchopra039@gmail.com">vaibhavchopra039@gmail.com</a> · <a href="tel:+917015867715">+91 70158 67715</a></p><a className="button button-light" href="mailto:vaibhavchopra039@gmail.com">Say hello <span>↗</span></a></div></section></main><footer><span>© 2026 Vaibhav Chopra</span><span>Senior Data Scientist / AI Engineer · Pune, India</span><div><a href="https://www.linkedin.com/in/vaibhav-chopra-4a226a21b/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://www.kaggle.com/vaibhavchopra2" target="_blank" rel="noreferrer">Kaggle</a><a href="mailto:vaibhavchopra039@gmail.com">Email</a></div></footer>{selectedProject && <CaseStudyModal project={selectedProject} onClose={() => setSelectedProject(null)} />}</div>
  )
}

function ProjectCard({ project, onOpen }) { return <article className="project-card reveal" onClick={onOpen} onKeyDown={(event) => event.key === 'Enter' && onOpen()} role="button" tabIndex="0"><div className="project-top"><span className="project-number">{project.number}</span><span className="project-eyebrow">{project.eyebrow}</span><button className="case-study-button" onClick={(event) => { event.stopPropagation(); onOpen() }}>View case study <span>↗</span></button></div><div className="project-body"><div className="project-copy"><h3>{project.title}</h3><p>{project.solution}</p><strong>{project.impact}</strong><div className="tech-pills">{project.tech.map((tech) => <span key={tech}>{tech}</span>)}</div></div><div className="flow"><span className="flow-label">SYSTEM FLOW</span>{project.flow.map((step, index) => <div className="flow-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < project.flow.length - 1 && <i>↓</i>}</div>)}</div></div><div className="project-cta">Click anywhere to explore the case study <span>↗</span></div></article> }
function AskVaibhav() { const [query, setQuery] = useState(''); const inputRef = useRef(null); const normalizedQuery = query.trim().toLowerCase(); const results = normalizedQuery ? searchItems.filter((item) => `${item.type} ${item.title} ${item.text}`.toLowerCase().includes(normalizedQuery)).slice(0, 4) : searchItems.slice(0, 3); useEffect(() => { const focusSearch = (event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); inputRef.current?.focus() } }; window.addEventListener('keydown', focusSearch); return () => window.removeEventListener('keydown', focusSearch) }, []); return <section className="ask-section section-pad" id="ask"><div className="ask-shell reveal"><div className="ask-heading"><div><p className="section-kicker">/ ASK VAIBHAV</p><h2>Search the work<br /><em>behind the numbers.</em></h2></div><p>Ask about projects, experience, awards, skills or location. Everything here is local, fast and recruiter-friendly.</p></div><div className="ask-input-wrap"><span>⌕</span><input ref={inputRef} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try: What has Vaibhav built with RAG?" aria-label="Search Vaibhav's portfolio" /><kbd>⌘ K</kbd></div><div className="ask-suggestions">{['RAG projects', 'Awards', 'Experience', 'Independent builds'].map((suggestion) => <button key={suggestion} onClick={() => setQuery(suggestion)}>{suggestion}<span>↗</span></button>)}</div><div className="ask-results" aria-live="polite">{results.length ? results.map((item) => <a className="ask-result" href={item.href} key={item.title}><span>{item.type}</span><div><h3>{item.title}</h3><p>{item.text}</p></div><i>↗</i></a>) : <div className="ask-empty">No exact match yet. Try “projects”, “skills”, “awards” or “experience”.</div>}</div></div></section> }
function SecondaryProjectCard({ project, onOpen }) { return <article className="secondary-project-card reveal" onClick={onOpen} onKeyDown={(event) => event.key === 'Enter' && onOpen()} role="button" tabIndex="0"><div className="secondary-project-top"><span>{project.number}</span><span>{project.eyebrow}</span></div><h3>{project.title}</h3><p>{project.solution}</p><strong>{project.impact}</strong><span className="card-arrow">↗</span></article> }
function Metric({ number, suffix, label }) { const ref = useRef(null); const [count, setCount] = useState(0); useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { let start = 0; const end = Number(number); const timer = setInterval(() => { start += Math.max(1, Math.ceil(end / 28)); if (start >= end) { start = end; clearInterval(timer) } setCount(start) }, 35); observer.disconnect() } }, { threshold: 0.7 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect() }, [number]); return <div className="metric" ref={ref}><strong>{count}<span>{suffix}</span></strong><p>{label}</p></div> }
function CaseStudyModal({ project, onClose }) { useEffect(() => { document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = '' } }, []); return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><span className="section-kicker">/ CASE STUDY {project.number} · {project.eyebrow}</span><h2>{project.title}</h2><div className="modal-columns"><div><h3>The challenge</h3><p>{project.problem}</p></div><div><h3>What I built</h3><p>{project.solution}</p></div></div><div className="modal-detail"><h3>Why it mattered</h3><p>{project.detail}</p></div><div className="modal-architecture"><span>PRODUCT FLOW</span><strong>{project.architecture}</strong></div><div className="modal-impact"><span>Measured outcome</span><strong>{project.impact}</strong></div><div className="tech-pills">{project.tech.map((tech) => <span key={tech}>{tech}</span>)}</div>{project.url && <a className="modal-project-link" href={project.url} target="_blank" rel="noreferrer">Open original project page <span>↗</span></a>}</div></div> }

export default App
